version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # location of package manifest 
    schedule:
      interval: "daily"  
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
